# Default values for jarvis-p1-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronjob:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  p1USBDevicePath: /dev/ttyUSB0
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  ttlSecondsAfterFinished: 3600

config:
  natsHost: jarvis-nats
  natsSubject: jarvis-measurements
  configYaml: |
    location: My Home
    sampleConfigs:
    - entityType: ENTITY_TYPE_TARIFF
      entityName: Sagemcom XS210
      sampleType: SAMPLE_TYPE_ELECTRICITY_CONSUMPTION
      sampleName: Levering dal
      metricType: METRIC_TYPE_COUNTER
      valueMultiplier: 3600000
      prefix: 1-0:1.8.1
      valueStartIndex: 10
      valueLength: 10
    - entityType: ENTITY_TYPE_TARIFF
      entityName: Sagemcom XS210
      sampleType: SAMPLE_TYPE_ELECTRICITY_CONSUMPTION
      sampleName: Levering normaal
      metricType: METRIC_TYPE_COUNTER
      valueMultiplier: 3600000
      prefix: 1-0:1.8.2
      valueStartIndex: 10
      valueLength: 10
    - entityType: ENTITY_TYPE_TARIFF
      entityName: Sagemcom XS210
      sampleType: SAMPLE_TYPE_ELECTRICITY_PRODUCTION
      sampleName: Teruglevering dal
      metricType: METRIC_TYPE_COUNTER
      valueMultiplier: 3600000
      prefix: 1-0:2.8.1
      valueStartIndex: 10
      valueLength: 10
    - entityType: ENTITY_TYPE_TARIFF
      entityName: Sagemcom XS210
      sampleType: SAMPLE_TYPE_ELECTRICITY_PRODUCTION
      sampleName: Teruglevering normaal
      metricType: METRIC_TYPE_COUNTER
      valueMultiplier: 3600000
      prefix: 1-0:2.8.2
      valueStartIndex: 10
      valueLength: 10

logLevel: debug

image:
  repository: jsalverda/jarvis-p1-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  # Specifies whether roles and bindings should be created
  enable: true

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
