location: My Home
sampleConfigs:
- entityType: ENTITY_TYPE_TARIFF
  entityName: Sagemcom XS210
  sampleType: SAMPLE_TYPE_ELECTRICITY_CONSUMPTION
  sampleName: Levering dal
  metricType: METRIC_TYPE_COUNTER
  valueMultiplier: 3600000
  prefix: 1-0:1.8.1
  valueStartIndex: 10
  valueLength: 10
- entityType: ENTITY_TYPE_TARIFF
  entityName: Sagemcom XS210
  sampleType: SAMPLE_TYPE_ELECTRICITY_CONSUMPTION
  sampleName: Levering normaal
  metricType: METRIC_TYPE_COUNTER
  valueMultiplier: 3600000
  prefix: 1-0:1.8.2
  valueStartIndex: 10
  valueLength: 10
- entityType: ENTITY_TYPE_TARIFF
  entityName: Sagemcom XS210
  sampleType: SAMPLE_TYPE_ELECTRICITY_PRODUCTION
  sampleName: Teruglevering dal
  metricType: METRIC_TYPE_COUNTER
  valueMultiplier: 3600000
  prefix: 1-0:2.8.1
  valueStartIndex: 10
  valueLength: 10
- entityType: ENTITY_TYPE_TARIFF
  entityName: Sagemcom XS210
  sampleType: SAMPLE_TYPE_ELECTRICITY_PRODUCTION
  sampleName: Teruglevering normaal
  metricType: METRIC_TYPE_COUNTER
  valueMultiplier: 3600000
  prefix: 1-0:2.8.2
  valueStartIndex: 10
  valueLength: 10