name: Build

on: [push, pull_request]

jobs:
  gitversion:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

  # run `cargo vendor` and cache it
  # vendor_sources:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/cache@v3
  #     name: Update crate cargo-vendor cache
  #     id: vendor_cache
  #     with:
  #       path: |
  #         .cargo
  #         vendor
  #       key: cargo-vendor-release-${{ hashFiles('**/Cargo.lock') }}
  #       restore-keys: |
  #         cargo-vendor-release
  #         cargo-vendor
  #       enableCrossOsArchive: true
  #   - uses: actions/cache@v3
  #     name: Update cargo registry cache
  #     if: steps.vendor_cache.outputs.cache-hit != 'true'
  #     with:
  #       path: |
  #         ~/.cargo/bin/
  #         ~/.cargo/registry/index/
  #         ~/.cargo/registry/cache/
  #         ~/.cargo/git/db/
  #       key: ${{ runner.os }}-cargo-cache-release-${{ hashFiles('**/Cargo.lock') }}
  #       restore-keys: |
  #         ${{ runner.os }}-cargo-cache-release
  #         ${{ runner.os }}-cargo-cache
  #   - name: Vendor sources
  #     if: steps.vendor_cache.outputs.cache-hit != 'true'
  #     run: |
  #       mkdir -p .cargo
  #       mkdir -p vendor
  #       cargo vendor --versioned-dirs --locked >.cargo/config.toml

  docker:
    runs-on: ubuntu-latest
    # needs: [gitversion, vendor_sources]
    needs: [gitversion]
    env:
      GITVERSION_SEMVER: ${{ needs.gitversion.outputs.semVer }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            target: x86_64-unknown-linux-musl
          - platform: linux/arm64
            target: aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/cache/restore@v3
      #   with:
      #     path: |
      #       .cargo
      #       vendor
      #     key: cargo-vendor-release-${{ hashFiles('**/Cargo.lock') }}
      #     enableCrossOsArchive: true
      #     fail-on-cache-miss: true
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            jsalverda/jarvis-p1-exporter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ needs.gitversion.outputs.semVer }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            CARGO_BUILD_TARGET=${{ matrix.target }}
            CARGO_NET_OFFLINE=true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  helm:
    runs-on: ubuntu-latest
    needs: [gitversion, docker]
    env:
      GITVERSION_SEMVER: ${{ needs.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.1
      - run: helm lint --with-subcharts helm/jarvis-p1-exporter
      - run: helm package --app-version $GITVERSION_SEMVER --version $GITVERSION_SEMVER --dependency-update helm/jarvis-p1-exporter
      - uses: actions/checkout@v2
        with:
          repository: JorritSalverda/helm-charts
          ref: master
          path: helm-charts
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: |
          mkdir -p helm-charts/charts
          cp jarvis-p1-exporter-${GITVERSION_SEMVER}.tgz helm-charts/charts
          cd helm-charts
          helm repo index --url https://helm.jorritsalverda.com/ .
          git config user.email 'bot@estafette.io'
          git config user.name 'estafette-bot'
          git add --all
          git commit --allow-empty -m "jarvis-p1-exporter $GITVERSION_SEMVER"
          git push origin master

  tag:
    runs-on: ubuntu-latest
    needs: [gitversion, docker, helm]
    env:
      GITVERSION_SEMVER: ${{ needs.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          git tag -f $GITVERSION_SEMVER
          git push origin $GITVERSION_SEMVER
