name: Build

on: [push, pull_request]

jobs:
  gitversion:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

  docker:
    runs-on: ubuntu-latest
    needs: gitversion
    env:
      GITVERSION_SEMVER: ${{ needs.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            jsalverda/jarvis-p1-exporter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ needs.gitversion.outputs.semVer }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile.armv8
          platforms: linux/arm/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=jsalverda/jarvis-p1-exporterbuild-cache
          cache-to: type=registry,ref=jsalverda/jarvis-p1-exporter-build-cache,mode=max
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=jsalverda/jarvis-p1-exporterbuild-cache
          cache-to: type=registry,ref=jsalverda/jarvis-p1-exporter-build-cache,mode=max

  helm:
    runs-on: ubuntu-latest
    needs: [gitversion, docker]
    env:
      GITVERSION_SEMVER: ${{ needs.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.1
      - run: helm lint --with-subcharts helm/jarvis-p1-exporter
      - run: helm package --app-version $GITVERSION_SEMVER --version $GITVERSION_SEMVER --dependency-update helm/jarvis-p1-exporter
      - uses: actions/checkout@v2
        with:
          repository: JorritSalverda/helm-charts
          ref: master
          path: helm-charts
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: |
          mkdir -p helm-charts/charts
          cp jarvis-p1-exporter-${GITVERSION_SEMVER}.tgz helm-charts/charts
          cd helm-charts
          helm repo index --url https://helm.jorritsalverda.com/ .
          git config user.email 'bot@estafette.io'
          git config user.name 'estafette-bot'
          git add --all
          git commit --allow-empty -m "jarvis-p1-exporter $GITVERSION_SEMVER"
          git push origin master

  tag:
    runs-on: ubuntu-latest
    needs: [gitversion, docker, helm]
    env:
      GITVERSION_SEMVER: ${{ needs.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          git tag -f $GITVERSION_SEMVER
          git push origin $GITVERSION_SEMVER
